-- MySQL Script generated by MySQL Workbench
-- sex 24 jan 2020 17:57:56 -04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dataset-workbench
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dataset-workbench
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dataset-workbench` DEFAULT CHARACTER SET utf8 ;
USE `dataset-workbench` ;

-- -----------------------------------------------------
-- Table `dataset-workbench`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataset-workbench`.`user` (
  `user_id` VARCHAR(100) NOT NULL,
  `semester_id` VARCHAR(10) NOT NULL,
  `class_number` INT NOT NULL,
  `course_id` INT NOT NULL,
  `course_name` VARCHAR(50) NOT NULL,
  `inst_id_curr` INT NOT NULL,
  `inst_name_curr` VARCHAR(100) NULL,
  `high_school_name` VARCHAR(100) NULL,
  `school_type` VARCHAR(20) NULL,
  `shift` VARCHAR(25) NULL,
  `graduation_year` INT NULL,
  `has_pc` VARCHAR(4) NULL,
  `has_internet` VARCHAR(4) NULL,
  `speed_internet` VARCHAR(15) NULL,
  `prev_exp_lang` VARCHAR(4) NULL,
  `language` VARCHAR(100) NULL,
  `worked` VARCHAR(6) NULL,
  `company_name` VARCHAR(100) NULL,
  `share_pc` VARCHAR(4) NULL,
  `year_started_work` VARCHAR(4) NULL,
  `year_stoped_work` VARCHAR(4) NULL,
  `other_degree` VARCHAR(4) NULL,
  `inst_name_prev` VARCHAR(100) NULL,
  `name_other_degree` VARCHAR(100) NULL,
  `year_started_prev_degree` INT NULL,
  `year_stoped_prev_degree` INT NULL,
  `sex` VARCHAR(15) NULL,
  `year_birth` INT NULL,
  `civil_status` VARCHAR(15) NULL,
  `have_kids` VARCHAR(4) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dataset-workbench`.`assessment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataset-workbench`.`assessment` (
  `assessment_id` VARCHAR(20) NOT NULL,
  `semester_id` VARCHAR(10) NULL,
  `assessment_title` VARCHAR(200) NULL,
  `class_name` VARCHAR(200) NULL,
  `class_number` INT NULL,
  `start` DATETIME NULL,
  `end` DATETIME NULL,
  `language` VARCHAR(70) NULL,
  `codemirror_mode` VARCHAR(70) NULL,
  `type` VARCHAR(45) NULL,
  `weight` INT NULL,
  `total_exercises` INT NULL,
  PRIMARY KEY (`assessment_id`),
  UNIQUE INDEX `assessment_id_UNIQUE` (`assessment_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dataset-workbench`.`user_assessment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataset-workbench`.`user_assessment` (
  `grade` FLOAT NULL,
  `number_exercises` INT NULL,
  `incorrect` INT NULL,
  `blank` INT NULL,
  `correct` INT NULL,
  `user_id` VARCHAR(100) NOT NULL,
  `assessment_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`user_id`, `assessment_id`),
  INDEX `fk_user1` (`user_id` ASC),
  INDEX `fk_assessment1` (`assessment_id` ASC),
  CONSTRAINT `fk_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `dataset-workbench`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assessment1`
    FOREIGN KEY (`assessment_id`)
    REFERENCES `dataset-workbench`.`assessment` (`assessment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dataset-workbench`.`executions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataset-workbench`.`executions` (
  `exercise_id` INT NOT NULL,
  `general_variation_submit` INT NULL,
  `mean_variations_submit` FLOAT NULL,
  `amount_submit` INT NULL,
  `amount_correct_submit` INT NULL,
  `amount_incorrect_submit` INT NULL,
  `general_variation_test` INT NULL,
  `mean_variations_test` FLOAT NULL,
  `amount_test` INT NULL,
  `done` VARCHAR(3) NULL,
  `user_id` VARCHAR(100) NOT NULL,
  `assessment_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`user_id`, `assessment_id`, `exercise_id`),
  INDEX `fk_assessment2` (`assessment_id` ASC),
  INDEX `fk_user2` (`user_id` ASC),
  INDEX `exercise_id` (`exercise_id` ASC),
  CONSTRAINT `fk_user2`
    FOREIGN KEY (`user_id`)
    REFERENCES `dataset-workbench`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assessment2`
    FOREIGN KEY (`assessment_id`)
    REFERENCES `dataset-workbench`.`assessment` (`assessment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dataset-workbench`.`submition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataset-workbench`.`submition` (
  `submition_id` INT NOT NULL AUTO_INCREMENT,
  `submition_datetime` DATETIME NULL,
  `user_id` VARCHAR(100) NOT NULL,
  `assessment_id` VARCHAR(20) NOT NULL,
  `exercise_id` INT NOT NULL,
  PRIMARY KEY (`submition_id`, `user_id`, `assessment_id`, `exercise_id`),
  CONSTRAINT `fk_execution1`
    FOREIGN KEY (`user_id` , `assessment_id` , `exercise_id`)
    REFERENCES `dataset-workbench`.`executions` (`user_id` , `assessment_id` , `exercise_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dataset-workbench`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataset-workbench`.`test` (
  `test_id` INT NOT NULL AUTO_INCREMENT,
  `test_datetime` DATETIME NULL,
  `user_id` VARCHAR(100) NOT NULL,
  `assessment_id` VARCHAR(20) NOT NULL,
  `exercise_id` INT NOT NULL,
  PRIMARY KEY (`test_id`, `user_id`, `assessment_id`, `exercise_id`),
  CONSTRAINT `fk_execution2`
    FOREIGN KEY (`user_id` , `assessment_id` , `exercise_id`)
    REFERENCES `dataset-workbench`.`executions` (`user_id` , `assessment_id` , `exercise_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
